version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/services/incident"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels: ["dependencies", "backend"]

  - package-ecosystem: "docker"
    directory: "/services/incident"
    schedule:
      interval: "weekly"
    labels: ["dependencies", "docker"]

  - package-ecosystem: "docker"
    directory: "/infra"
    schedule:
      interval: "weekly"
    labels: ["dependencies", "infra"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels: ["dependencies", "ci"]
