/**
 * JUKWA Incident Categories & Severity Scores
 * Source: Tech Bible Part I §1.1, Architecture §5.5
 */

export const INCIDENT_CATEGORIES = {
  SECURITY: [
    "ROBBERY", "ASSAULT", "SUSPICIOUS_ACTIVITY", "NOISE_DISTURBANCE", 
    "VANDALISM", "BURGLARY", "GANG_ACTIVITY", "ILLEGAL_FIREARMS"
  ],
  TRAFFIC: [
    "ACCIDENT", "CONGESTION", "BROKEN_SIGNAL", "ILLEGAL_PARKING", 
    "MATATU_VIOLATION", "ROAD_CLOSURE", "DRUNK_DRIVING", "STALLED_VEHICLE"
  ],
  INFRASTRUCTURE: [
    "POTHOLE", "BURST_PIPE", "ELECTRICAL_FAULT", "GARBAGE", 
    "OPEN_MANHOLE", "BROKEN_STREETLIGHT", "ILLEGAL_DUMPING", "VANDALIZED_INFRA"
  ],
  CIVIC: [
    "LAND_DISPUTE", "ENVIRONMENTAL_POLLUTION", "PUBLIC_HEALTH_RISK", 
    "CORRUPTION", "GRIEVANCE", "ANIMAL_WANDERING", "UNAUTHORIZED_CONSTRUCTION"
  ],
  EMERGENCY: [
    "FIRE", "MEDICAL_EMERGENCY", "ACTIVE_CRIME", "CATASTROPHIC_FAILURE"
  ]
} as const;

export const SEVERITY_LEVELS = {
  LOW: 1,
  MODERATE: 2,
  STANDARD: 3,
  HIGH: 4,
  CRITICAL: 5
} as const;

// Flattened list for validation
export const ALL_CATEGORIES = Object.values(INCIDENT_CATEGORIES).flat();
